### ISSUE TITLE
IndexError: index 3 is out of bounds for dimension 0 with size 3

### ISSUE THREAD

**Issue by ankitAMD** [cfotache/pytorch_custom_yolo_training#1]
when i executing and trained the model on custom images this error comes .
![Error2](https://user-images.githubusercontent.com/17083641/69721132-339e2900-113a-11ea-9b91-5336b1f20cff.png)

  Please Help and explain the error comes.Thank you .

**Comment by mariontan** [comment]
I also have the same issue was this problem resolved?

Does it have something to do with the class labels?

**Comment by SriramPingali** [comment]
I faced a similar issue with my run. It appears that we are supposed to configure the yolo.cfg file. 
Please go through the "config file" section of this [article](https://towardsdatascience.com/training-yolo-for-object-detection-in-pytorch-with-your-custom-dataset-the-simple-way-1aa6f56cf7d9)
and correspondingly change the classes and filter sizes wrt your requirement in the yolo.cfg file.

Hope this helps!

**Comment by mariontan** [comment]
Thank you very much. Yes it may have been a configuration problem. I refollowed the steps and it worked.
