### ISSUE TITLE
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 

### ISSUE THREAD

**Issue by ankitAMD** [cfotache/pytorch_custom_yolo_training#2]
when i executing and trained the model on custom images this error comes .
![error](https://user-images.githubusercontent.com/17083641/69722068-3732af80-113c-11ea-8e41-36ae8f96d3a7.png)

  Please Help .

**Comment by realsidg** [comment]
> You need one .txt file for each image (same name, different extension, separate folder). Each file contains just one row, in this format:
> 
> class x y width height
> 
> So, for example one file (for class 1) could be:
> 
> 1 0.351466 0.427083 0.367168 0.570486
> 
> Note that the coordinates and size are as a proportion of the entire image size. For example, if the file is 600x600px, a coordinate of (200,300) would be represented as (0.333333, 0.5).

[Original Article](
https://towardsdatascience.com/training-yolo-for-object-detection-in-pytorch-with-your-custom-dataset-the-simple-way-1aa6f56cf7d9)
